ci: update supported node versions
imgix/luminous pull request #509
Opened 2020-12-04 04:08 UTC by sherwinski

Adds [currently supported](https://nodejs.org/en/about/releases/) LTS node versions to CI.

TODO: remove EOL'd versions in a future major release

2020-12-04 11:31 UTC, frederickfogerty requested changes
Same comment as in drift

2020-12-04 11:32 UTC, frederickfogerty commented
I'm just wondering if removing an EOL release warrants a major bump. We're not necessarily _stopping_ this code from working on that release, and that release is already unsupported anyway, so we're technically not breaking any code that is running on a _supported_ node version.

2020-12-08 04:34 UTC, sherwinski commented
That's a good point, and I guess it really depends. It definitely doesn't have to wait until a major release unless we want to be overly cautious (as I suggested). I was mainly concerned for users who might be on older node versions suddenly experiencing issues after bumping to a minor or patch. It's true that we're not necessarily stopping this library from working on that release, but I was afraid we'd lose track exactly when it deviated. At least this way, we'd be making that choice deliberately.

All that said, I'm not saying we **shouldn't** use `stable` and `lts/*`, we just need to decide as a team what our stance is on supporting a particular node version and how it relates to our library release cycle. I am fine with dropping support for EOL versions as they occur if we think that's reasonable.

2020-12-10 06:53 UTC, frederickfogerty reviewed
Looking good 👍

2020-12-10 06:53 UTC, frederickfogerty approved these changes

2020-12-11 23:57 UTC, merged